require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'Gemfile'
    - '**/config.ru'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
